### ISSUE TITLE
[Feature] Modify DeepSpeech's STT output text styles

### ISSUE THREAD

**Issue by rayleighko** [teamthesol/react-DeepSpeech#24]
**Is your feature request related to a problem? Please describe.**
Current DeepSpeech replaces existing 'Input' values ​​when converted. But, the way we wanted was that DeepSpeech should be merged with the existing 'input' value.

Therefore, it is necessary to add the converted data below the existing 'input' value.

**Describe the solution you'd like**
What about wrapping the existing transformed input with a particular string, such as `` `, And appending it to the end of the existing 'input' value?

**Comment by hojihun5516** [comment]
done
